[package]
name = "tagger"
version = "1.0.3"
authors = ["mz <emgyrz@gmail.com>"]
edition = "2018"

[dependencies]
git2 = "0.9"
tempdir = "0.3"
dirs = "2"
semver = "0.9"
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
docopt = "1.1"
